SCRIPT_NAME=elf
TEMPLATE_NAME=generic
EXTRA_EM_FILE=genelf
OUTPUT_FORMAT="elf32-mrisc32"
MAXPAGESIZE="CONSTANT (MAXPAGESIZE)"
ARCH=mrisc32
EMBEDDED=yes
ENTRY=_start
TEXT_START_ADDR=0x00000200
OTHER_BSS_SYMBOLS="${CREATE_SHLIB+PROVIDE (}__bss_start = .${CREATE_SHLIB+)};"
OTHER_BSS_END_SYMBOLS="PROVIDE (__bss_end = .);"
